packages:
  # 包含所有 packages 目录下的项目
  - "packages/*"
  - "packages/plugins/*"
  - "!packages/plugins"

onlyBuiltDependencies:
  - "esbuild"

catalogs:
  types:
    "@types/js-yaml": ^4.0.9
    "@types/linkify-it": ^5.0.0
    "@types/mdurl": ^2.0.0
    "@types/node": ^24.1.0
  lint:
    "@eslint/js": ^9.32.0
    eslint: ^9.32.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.3
    eslint-plugin-simple-import-sort: ^12.1.1
    globals: ^16.3.0
    jiti: ^2.5.1
    prettier: ^3.6.2
    typescript-eslint: ^8.38.0
  prod:
    js-yaml: ^4.1.0
    katex: ^0.16.22
  build:
    vite: ^7.0.6
    vite-plugin-dts: ^4.5.4
    rimraf: ^6.0.1
  test:
    cheerio: ^1.1.2
    "@vitest/coverage-istanbul": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: ^3.2.4
    "@sindresorhus/slugify": ^2.2.1
  doc:
    vitepress: "2.0.0-alpha.9"

catalog:
  typescript: 5.8.3
  uc.micro-for-enhancer: workspace:*
