name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '20' ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: pnpm install

    - name: Test
      run: pnpm test

    - name: Upload coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
