name: Coverage

on:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Pnpm
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Run tests with coverage
        run: pnpm test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          flags: core,entities,linkify-it,md-url,plugin-abbr,plugin-anchor,plugin-attrs
